config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'admin/index'
  root 'admin#index'

  resources :patients
  resources :comments
  resources :receipts

  get '/comments/new/:nr_cpf', action: :new, controller: 'comments'
  get '/vizualizar_comentarios/:nr_cpf', action: :index, controller: 'comments'

    #get '/gerar_recigo/:nr_cpf', action: :new, controller: 'receipts'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :patient
  accepts_nested_attributes_for :patient

end

app/models/patient.rb
class Patient < ApplicationRecord

  has_one_attached :photo

end

app/models/receipt.rb
class Receipt < ApplicationRecord

  belongs_to :patient
  accepts_nested_attributes_for :patient

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @comment.data_comentario = Date.new
    @patient = Patient.find_by_cpf(params[:nr_cpf])
    @comment.patient = @patient
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.data_comentario = Time.new
    @comment.patient = Patient.find_by_cpf(params[:patient][:cpf])
    @comment.save
    redirect_to controller: 'comments', action: 'index', nr_cpf: params[:patient][:cpf]
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @comment
    else
      render 'edit'
    end
  end

  def index
    @patient = Patient.find_by_cpf(params['nr_cpf'])
    @comments = Array.new
    @comments = Comment.where(patient_id: @patient.id)
  end

  private
  def comment_params
    params.require(:comment).permit( :conteudo, patient_attributes: [:cpf, :nome])
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.save
    redirect_to patients_path
  end

  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    if @patient.update(patient_params)
      redirect_to patients_path
    else
      render 'edit'
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  private
  def patient_params
    params.require(:patient).permit(:nome, :cpf, :data_nascimento, :telefone, :photo)
  end

end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

  def new
    @receipt = Receipt.new
    @patients = Patient.all.map { |patient| [patient.nome, patient.id]}
  end

  def create
    @receipt = Receipt.new(receipt_params)
    # @receipt.patient = Patient.find_by_cpf(params[:patient][:cpf])
    @receipt.save
    redirect_to receipts_path
  end

  def index
    @receipts = Receipt.all
  end

  def show
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice No. #{@receipt.id}",
               page_size: 'A4',
               template: "receipts/show.html.erb",
               layout: "pdf.html",
               orientation: "Landscape",
               lowquality: true,
               zoom: 1,
               dpi: 75
      end
    end

  end

  def update
    @receipt = Receipt.find(params[:id])

    if @receipt.update(receipt_params)
      redirect_to receipts_path
    else
      render 'edit'
    end
  end

  def edit
    @receipt = Receipt.find(params[:id])
    @patients = Patient.all.map { |patient| [patient.nome, patient.id]}
  end

  private
  def receipt_params
    params.require(:receipt).permit(:valor, :descricao_tratamento, :patient_id)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/admin/index.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">

          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">



<br />
      <h2>Section title</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
          <tr>
            <th>#</th>
            <th>Header</th>
            <th>Header</th>
            <th>Header</th>
            <th>Header</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>1,001</td>
            <td>Lorem</td>
            <td>ipsum</td>
            <td>dolor</td>
            <td>sit</td>
          </tr>
          <tr>
            <td>1,002</td>
            <td>amet</td>
            <td>consectetur</td>
            <td>adipiscing</td>
            <td>elit</td>
          </tr>
          <tr>
            <td>1,003</td>
            <td>Integer</td>
            <td>nec</td>
            <td>odio</td>
            <td>Praesent</td>
          </tr>
          <tr>
            <td>1,003</td>
            <td>libero</td>
            <td>Sed</td>
            <td>cursus</td>
            <td>ante</td>
          </tr>
          <tr>
            <td>1,004</td>
            <td>dapibus</td>
            <td>diam</td>
            <td>Sed</td>
            <td>nisi</td>
          </tr>
          <tr>
            <td>1,005</td>
            <td>Nulla</td>
            <td>quis</td>
            <td>sem</td>
            <td>at</td>
          </tr>
          <tr>
            <td>1,006</td>
            <td>nibh</td>
            <td>elementum</td>
            <td>imperdiet</td>
            <td>Duis</td>
          </tr>
          <tr>
            <td>1,007</td>
            <td>sagittis</td>
            <td>ipsum</td>
            <td>Praesent</td>
            <td>mauris</td>
          </tr>
          <tr>
            <td>1,008</td>
            <td>Fusce</td>
            <td>nec</td>
            <td>tellus</td>
            <td>sed</td>
          </tr>
          <tr>
            <td>1,009</td>
            <td>augue</td>
            <td>semper</td>
            <td>porta</td>
            <td>Mauris</td>
          </tr>
          <tr>
            <td>1,010</td>
            <td>massa</td>
            <td>Vestibulum</td>
            <td>lacinia</td>
            <td>arcu</td>
          </tr>
          <tr>
            <td>1,011</td>
            <td>eget</td>
            <td>nulla</td>
            <td>Class</td>
            <td>aptent</td>
          </tr>
          <tr>
            <td>1,012</td>
            <td>taciti</td>
            <td>sociosqu</td>
            <td>ad</td>
            <td>litora</td>
          </tr>
          <tr>
            <td>1,013</td>
            <td>torquent</td>
            <td>per</td>
            <td>conubia</td>
            <td>nostra</td>
          </tr>
          <tr>
            <td>1,014</td>
            <td>per</td>
            <td>inceptos</td>
            <td>himenaeos</td>
            <td>Curabitur</td>
          </tr>
          <tr>
            <td>1,015</td>
            <td>sodales</td>
            <td>ligula</td>
            <td>in</td>
            <td>libero</td>
          </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script src="dashboard.js"></script>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>


  <div class="form-group">
    <div>
      <input type="text" readonly class="form-control-plaintext" value="<%=@patient.nome %>">
    </div>
  </div>

  <div style="display: none">
  <%= fields_for :patient, @comment.patient do |patient_fields| %>
    Nome: <%= patient_fields.text_field :nome %>
    cpf: <%= patient_fields.text_field :cpf %>
  <% end %>
  </div>

  <div class="form-group">
    <%= form.label :conteudo %><br>
    <%= form.text_area :conteudo, :class => 'form-control' , rows: "8" %>
  </div>



  <%= form.submit 'Salvar Evolução', :class => 'btn btn-primary btn-sm' %>

<% end %>

app/views/comments/edit.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />
      <h2>Editar Paciente</h2>
      <div class="table-responsive">

        <%= render 'form' %>

      </div>
    </main>

  </div>
</div>

app/views/comments/index.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />

        <% @comments.each do |comment| %>
        <div class="alert alert-success" role="alert">
          <h4 class="alert-heading"><%=comment.data_comentario %></h4>
          <p><%=comment.conteudo %></p>
        </div>
        <br />
        <% end %>

      </main>
  </div>
</div>

app/views/comments/new.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />
      <h2>Nova Evolução de Paciente</h2>
      <div class="table-responsive">

        <%= render 'form' %>

      </div>
    </main>

  </div>
</div>

app/views/comments/show.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />

      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">Data Comentário</th>
          <th scope="col">Conteúdo</th>
        </tr>
        </thead>
        <tbody>

        <% @comments.each do |comment| %>
          <tr>
            <td><%=comment.data_comentario %></td>
            <td><%=comment.conteudo %></td>
          </tr>
        <% end %>


        </tbody>
      </table>

      <button type="button" class="btn btn-primary btn-sm" onclick="location.href='/patients/new'">Adicionar Novo Paciente</button>

    </main>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Espacotrate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<html>
<head>
  <title>EspacoTrate</title>
  <%= wicked_pdf_stylesheet_link_tag "receipt" %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

</head>
<body>
<%= yield %>
</body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: @patient, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :nome %><br>
    <%= form.text_field :nome, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :data_nascimento %><br>
    <%= form.text_field :data_nascimento, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :telefone %><br>
    <%= form.text_field :telefone, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :photo %><br>
    <%= form.file_field :photo, :class => 'form-control' %>
  </div>

  <button type="button" class="btn btn-primary btn-sm" onclick="location.href='/patients'">Voltar</button>
  <%= form.submit 'Salvar Paciente', :class => 'btn btn-primary btn-sm' %>

<% end %>

app/views/patients/edit.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />
      <h2>Editar Paciente</h2>
      <div class="table-responsive">

        <%= render 'form' %>

      </div>
    </main>

  </div>
</div>

app/views/patients/index.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />

      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">CPF</th>
          <th scope="col">Data Nascimento</th>
          <th scope="col">Telefone</th>
          <th scope="col">Opções</th>
        </tr>
        </thead>
        <tbody>

        <% @patients.each do |patient| %>
          <tr>
            <td><%=patient.nome %></td>
            <td><%=patient.cpf %></td>
            <td><%=patient.data_nascimento %></td>
            <td><%=patient.telefone %></td>
            <td>
              <%= link_to 'Show', patient_path(patient) %> |
              <%= link_to 'Edit', edit_patient_path(patient) %>
            </td>
          </tr>
        <% end %>


        </tbody>
      </table>

      <button type="button" class="btn btn-primary btn-sm" onclick="location.href='/patients/new'">Adicionar Novo Paciente</button>

    </main>
  </div>
</div>

app/views/patients/new.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />
      <h2>Novo Paciente</h2>
      <div class="table-responsive">

        <%= render 'form' %>

      </div>
    </main>

  </div>
</div>

app/views/patients/show.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />
      <br />

      <form>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Nome</label>
          <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" value="<%=@patient.nome %>">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">CPF</label>
          <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" value="<%=@patient.cpf %>">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Telefone</label>
          <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" value="<%=@patient.telefone %>">
          </div>
        </div>
        <div class="form-group row">
          <label for="staticEmail" class="col-sm-2 col-form-label">Nome</label>
          <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="<%=@patient.data_nascimento %>">
          </div>
        </div>
        <% if @patient.photo.attached? %>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label ">Foto</label>
          <div class="col-sm-10">
            <%= image_tag @patient.photo %>
          </div>
        </div>
        <% end %>
        <br />
        <button type="button" class="btn btn-primary btn-sm" onclick="location.href='/comments/new/<%=@patient.cpf %>'">Cadastrar Evolução</button>
        <button type="button" class="btn btn-primary btn-sm" onclick="location.href='/vizualizar_comentarios/<%=@patient.cpf %>'">Visualizar Evoluções</button>

      </form>



    </main>


  </div>
</div>

app/views/receipts/_form.html.erb
<%= form_with(model: @receipt, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :patient %><br>
    <%= form.select :patient_id, options_for_select(@patients), {}, {required: 'true', autofocus: 'true', class: 'custom-select custom-select-lg mb-3'} %>

  </div>

  <div class="form-group">
    <%= form.label :descricao_tratamento %><br>
    <%= form.text_field :descricao_tratamento, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :valor %><br>
    <%= form.text_field :valor, :class => 'form-control' %>
  </div>

  <%= form.submit 'Salvar Recibo', :class => 'btn btn-primary btn-sm' %>

<% end %>

app/views/receipts/edit.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />
      <h2>Editar Redibo</h2>
      <div class="table-responsive">

        <%= render 'form' %>

      </div>
    </main>

  </div>
</div>

app/views/receipts/index.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />

      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">Nome Pessoa</th>
          <th scope="col">Valor</th>
          <th scope="col">Descrição Tratamento</th>
          <th scope="col">Opções</th>
        </tr>
        </thead>
        <tbody>

        <% @receipts.each do |receipt| %>
          <tr>
            <td><%=receipt.patient.nome %></td>
            <td><%=receipt.valor %></td>
            <td><%=receipt.descricao_tratamento %></td>
            <td>
              <%= link_to 'Show', receipt_path(receipt) %> |
              <%= link_to 'Edit', edit_receipt_path(receipt) %>
            </td>
          </tr>
        <% end %>


        </tbody>
      </table>

      <button type="button" class="btn btn-primary btn-sm" onclick="location.href='/receipts/new'">Adicionar Novo Recibo</button>

    </main>
  </div>
</div>

app/views/receipts/new.html.erb
<%= render :partial => './div_top' %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => './div_left' %>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

      <br />
      <h2>Novo Recibo de Paciente</h2>
      <div class="table-responsive">

        <%= render 'form' %>

      </div>
    </main>

  </div>
</div>

app/views/receipts/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<div class="container" >

<div>
  <img src="<%= asset_path( 'logo_espaco_trate.png' ) %>" />
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />


<div style="text-align: center">
  <strong>RECIBO</strong>
</div>

<br />
<br />
<br />
<br />

<div>
  <p>Através desse documento, Eu, <strong>Ludmilla Pereira Mota</strong>, inscrita no <strong>CPF 734.834.861-00</strong>, declaro que
    recebi do Sr.(a) <strong><%=@receipt.patient.nome %></strong>, CPF <strong><%=@receipt.patient.cpf %>,</strong> a quantia de <strong>R$
    <%=@receipt.valor %></strong>, correspondente à seguinte tratamento: <strong><%=@receipt.descricao_tratamento %></strong>.</p>
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />

<div>
  <hr style="border-color: black">
</div>
<div style="text-align: center">
  Ludmilla Pereira Mota
</div>

<br />
<br />
<br />
<br />
<br />
<br />

<div style="text-align: right">Goiania, <%= Time.now().strftime("%d/%m/%Y") %></div>
</div>